(()=>{
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const VIEWS={control:'Centro de Control',comms:'Comunicaciones',projects:'Proyectos',agents:'Agentes',automations:'Automatizaciones',memory:'Memoria',knowledge:'Base de Conocimiento',ai:'Universal Core',market:'Herramientas'};
  const state={view:'control',caps:null,performance:null,busy:false};

  function ensurePanel(){
    let panel=$('#universalPanel');
    if(panel)return panel;
    panel=document.createElement('section');
    panel.id='universalPanel';panel.className='v7-panel';panel.setAttribute('aria-hidden','true');
    panel.innerHTML=`<header class="v7-panel-head"><div><small>WAE OS ENTERPRISE</small><strong id="v7PanelTitle">Centro de Control</strong></div><div><button type="button" class="v7-refresh" id="v7Refresh">Actualizar</button><button type="button" class="v7-close" id="v7Close" aria-label="Cerrar">×</button></div></header><div class="v7-panel-body" id="v7PanelBody"></div>`;
    document.body.appendChild(panel);
    $('#v7Close',panel)?.addEventListener('click',closePanel);
    $('#v7Refresh',panel)?.addEventListener('click',()=>renderView(state.view,true));
    return panel;
  }
  function openPanel(view){state.view=view||'control';const p=ensurePanel();p.classList.add('open');p.setAttribute('aria-hidden','false');document.documentElement.classList.add('v7-panel-open');$('#drawer')?.classList.remove('open');$('#scrim')?.classList.remove('visible');renderView(state.view).catch(()=>{});}
  function closePanel(){const p=$('#universalPanel');p?.classList.remove('open');p?.setAttribute('aria-hidden','true');document.documentElement.classList.remove('v7-panel-open');}
  async function json(url,options){const r=await fetch(url,{cache:'no-store',...options});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.message||d?.error||`HTTP ${r.status}`);return d}
  async function loadCaps(force=false){if(state.caps&&!force)return state.caps;state.caps=await json('/api/capabilities');return state.caps}
  async function loadPerformance(force=false){if(state.performance&&!force)return state.performance;try{state.performance=await json('/api/performance')}catch{state.performance=null}return state.performance}
  const body=()=>$('#v7PanelBody');
  const runtime=()=>window.__iuLastRuntime||{};
  const fmtMs=v=>Number.isFinite(Number(v))&&Number(v)>0?`${Math.round(Number(v))} ms`:'—';
  const statusPill=(ok,label)=>`<span class="v7-pill ${ok?'ok':'muted'}">${esc(label)}</span>`;
  function setTitle(view){const t=$('#v7PanelTitle');if(t)t.textContent=VIEWS[view]||'Universal Core'}
  function card(label,value,detail=''){return `<article class="v7-stat"><small>${esc(label)}</small><strong>${esc(value)}</strong>${detail?`<span>${esc(detail)}</span>`:''}</article>`}

  async function renderControl(force=false){
    const [caps,perf]=await Promise.all([loadCaps(force),loadPerformance(force)]);const last=runtime(),tools=(caps.tools||[]),agents=(caps.agents||[]),configuredTools=tools.filter(x=>x.configured).length;
    const gate=perf?.performance||{};
    body().innerHTML=`<div class="v7-grid">${card('Estado',caps.ready?'Operativo':'Degradado',caps.version||'runtime')}${card('Agentes',String(agents.length),'roles disponibles')}${card('Herramientas',`${configuredTools}/${tools.length}`,'conectadas')}${card('Última latencia',fmtMs(last.latency_ms||last.latencyMs),'respuesta observada')}</div><section class="v7-section"><div class="v7-section-head"><div><small>RUNTIME</small><h3>Capacidades en vivo</h3></div>${statusPill(caps.generativeReady!==false,'Universal Core')}</div><div class="v7-live-list"><div><span>Memoria persistente</span><strong>${caps.memory?.configured?'Activa':'Continuidad local'}</strong></div><div><span>Respuesta estructurada</span><strong>${caps.responseSchema||'assistant-response/v1'}</strong></div><div><span>Streaming</span><strong>${gate.stream_ready===true?'Disponible':'Fail-closed'}</strong></div><div><span>Ruta adaptativa</span><strong>${gate.candidate_promotable===true?'Promovida':'Control seguro'}</strong></div></div></section><div class="v7-actions"><button data-v7-action="new-chat">Nueva conversación</button><button data-v7-action="workspace">Abrir Workspace</button><button data-v7-view="agents">Ver agentes</button><button data-v7-view="knowledge">Gestionar archivos</button></div>`;
  }

  async function renderAgents(force=false){const caps=await loadCaps(force);const agents=caps.agents||[];body().innerHTML=`<section class="v7-section"><div class="v7-section-head"><div><small>ORQUESTACIÓN</small><h3>Agentes disponibles</h3></div>${statusPill(true,`${agents.length} activos`)}</div><p class="v7-copy">Selecciona una especialidad. Universal Core conserva una sola identidad pública y cambia internamente la estrategia de trabajo.</p><div class="v7-agent-grid">${agents.map(a=>`<button type="button" class="v7-agent" data-agent="${esc(a.id)}"><strong>${esc(a.name||a.id)}</strong><span>${esc(a.description||'Especialidad operativa')}</span><small>${esc((a.tools||[]).join(' · ')||'sin herramientas obligatorias')}</small></button>`).join('')}</div></section>`}
  function localProjects(){try{return JSON.parse(localStorage.getItem('iu.projects')||'[]')}catch{return[]}}
  function saveProjects(list){localStorage.setItem('iu.projects',JSON.stringify(list.slice(0,40)))}
  function renderProjects(){const projects=localProjects();body().innerHTML=`<section class="v7-section"><div class="v7-section-head"><div><small>PROYECTOS</small><h3>Contextos de trabajo</h3></div>${statusPill(true,`${projects.length} guardados`)}</div><div class="v7-form"><input id="v7ProjectTitle" maxlength="80" placeholder="Nombre del proyecto"><textarea id="v7ProjectGoal" rows="3" maxlength="1200" placeholder="Objetivo, restricciones y resultado esperado"></textarea><button type="button" id="v7AddProject">Guardar proyecto</button></div><div class="v7-projects">${projects.length?projects.map((p,i)=>`<article><div><strong>${esc(p.title)}</strong><span>${esc(p.goal)}</span></div><div><button data-project-use="${i}">Usar</button><button data-project-delete="${i}" class="danger">Eliminar</button></div></article>`).join(''):'<p class="v7-empty">Aún no hay proyectos. Guarda uno para reutilizar su contexto en el chat.</p>'}</div><small class="v7-note">Los proyectos de esta vista se guardan en este dispositivo; las conversaciones y memoria del núcleo siguen su propio almacenamiento.</small></section>`}
  function renderComms(){const v=window.__waeVoice;const enabled=v?.enabled!==false;body().innerHTML=`<div class="v7-grid">${card('Voz',enabled?'Activa':'Desactivada','salida natural')}${card('Streaming',window.__iuStream?.enabled?'Disponible':'Restringido','sólo modelos verificados')}${card('Sesión',localStorage.getItem('iu.sessionId')?'Sincronizada':'Inicializando','identidad local')}</div><section class="v7-section"><h3>Canales de interacción</h3><p class="v7-copy">La interfaz usa voz, streaming verificado y continuidad automática sin exponer marcas de proveedores.</p><div class="v7-actions"><button data-v7-action="toggle-voice">${enabled?'Desactivar voz':'Activar voz'}</button><button data-v7-action="stop-voice">Detener reproducción</button></div></section>`}
  function renderMemory(){let messages=[];try{messages=JSON.parse(localStorage.getItem('wae.messages')||'[]')}catch{}const last=runtime(),cid=localStorage.getItem('iu.conversationId')||'';body().innerHTML=`<div class="v7-grid">${card('Conversación',cid?'Activa':'Nueva',cid?`${cid.slice(0,8)}…`:'sin id')}${card('Mensajes locales',String(Array.isArray(messages)?messages.length:0),'ventana reciente')}${card('Memorias recuperadas',String(Number(last.memory_count??last.memory?.recalled??0)),'última respuesta')}</div><section class="v7-section"><div class="v7-section-head"><div><small>MEMORIA</small><h3>Continuidad contextual</h3></div>${statusPill(true,'Activa')}</div><p class="v7-copy">Universal Core conserva continuidad de conversación y recupera contexto cuando el runtime lo permite. La interfaz no inventa porcentajes de uso de memoria.</p><div class="v7-actions"><button data-v7-action="new-chat">Iniciar conversación nueva</button></div></section>`}
  function renderKnowledge(){const files=window.__waeRuntimeAttachments||[];body().innerHTML=`<section class="v7-section"><div class="v7-section-head"><div><small>CONOCIMIENTO</small><h3>Archivos adjuntos</h3></div>${statusPill(true,`${files.length}/5`)}</div><p class="v7-copy">Los archivos de texto compatibles se incorporan a la siguiente misión. El contenido se limita antes de enviarse al runtime.</p><div class="v7-files">${files.length?files.map((f,i)=>`<article><div><strong>${esc(f.name)}</strong><span>${esc(f.type||'text/plain')}</span></div><small>${new Intl.NumberFormat('es-MX').format(String(f.text||'').length)} caracteres</small></article>`).join(''):'<p class="v7-empty">No hay archivos listos para la siguiente consulta.</p>'}</div><div class="v7-actions"><button data-v7-action="attach">Agregar archivos</button><button data-v7-action="clear-files">Limpiar adjuntos</button></div></section>`}
  async function renderAutomations(){body().innerHTML=`<section class="v7-section"><div class="v7-section-head"><div><small>EJECUCIÓN</small><h3>Tarea operativa</h3></div>${statusPill(true,'Runtime real')}</div><p class="v7-copy">Envía una tarea al endpoint operativo. El resultado se ejecuta con las mismas políticas de seguridad y fallback del núcleo.</p><div class="v7-form"><textarea id="v7Task" rows="5" maxlength="30000" placeholder="Ejemplo: analiza esta arquitectura y devuelve riesgos, prioridades y plan de ejecución"></textarea><button type="button" id="v7RunTask">Ejecutar tarea</button></div><div id="v7TaskResult"></div></section>`}
  async function renderTools(force=false){const caps=await loadCaps(force);const tools=caps.tools||[];body().innerHTML=`<section class="v7-section"><div class="v7-section-head"><div><small>CAPACIDADES</small><h3>Herramientas conectadas</h3></div>${statusPill(true,`${tools.filter(t=>t.configured).length} disponibles`)}</div><div class="v7-tool-list">${tools.map(t=>`<article><div><strong>${esc(t.id)}</strong><span>${esc(t.description||'Herramienta del núcleo')}</span></div>${statusPill(t.configured,t.configured?'Conectada':'No configurada')}</article>`).join('')||'<p class="v7-empty">No hay herramientas declaradas por el runtime.</p>'}</div></section>`}
  async function renderCore(force=false){const caps=await loadCaps(force);body().innerHTML=`<section class="v7-section"><div class="v7-core-mark">UC</div><h2>Universal Core</h2><p class="v7-copy">Núcleo operativo de WAE OS Enterprise para investigar, programar, analizar, diseñar, trabajar con archivos, memoria y ejecución asistida.</p><div class="v7-live-list"><div><span>Runtime</span><strong>${esc(caps.version||'activo')}</strong></div><div><span>Contrato</span><strong>${esc(caps.responseSchema||'assistant-response/v1')}</strong></div><div><span>Continuidad</span><strong>${caps.continuity?.configured?'Activa':'Limitada'}</strong></div></div></section>`}

  async function renderView(view,force=false){setTitle(view);const root=body();if(!root)return;root.innerHTML='<div class="v7-loading"><i></i><span>Sincronizando Universal Core…</span></div>';try{if(view==='control')return await renderControl(force);if(view==='agents')return await renderAgents(force);if(view==='projects')return renderProjects();if(view==='comms')return renderComms();if(view==='memory')return renderMemory();if(view==='knowledge')return renderKnowledge();if(view==='automations')return renderAutomations();if(view==='market')return await renderTools(force);if(view==='ai')return await renderCore(force);root.innerHTML='<p class="v7-empty">Este módulo aún no tiene una operación propia.</p>'}catch(e){root.innerHTML=`<div class="v7-error"><strong>No pude sincronizar este módulo.</strong><span>${esc(e.message||e)}</span><button type="button" id="v7Retry">Reintentar</button></div>`;$('#v7Retry')?.addEventListener('click',()=>renderView(view,true))}}

  function useProject(index){const p=localProjects()[index],input=$('#messageInput');if(!p||!input)return;input.value=`Proyecto: ${p.title}\n\nObjetivo: ${p.goal}\n\n`;input.dispatchEvent(new Event('input',{bubbles:true}));closePanel();input.focus()}
  async function runTask(){if(state.busy)return;const task=$('#v7Task')?.value.trim(),out=$('#v7TaskResult'),btn=$('#v7RunTask');if(!task||!out)return;state.busy=true;if(btn){btn.disabled=true;btn.textContent='Ejecutando…'}out.innerHTML='<div class="v7-loading"><i></i><span>Ejecutando tarea…</span></div>';try{const d=await json('/api/tasks',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({task,mode:localStorage.getItem('wae.mode')||'executive',sessionId:localStorage.getItem('iu.sessionId')||undefined})});const reply=String(d.reply||d.response?.content||'Tarea completada');out.innerHTML=`<article class="v7-task-result"><div>${window.__waeRich?.render?.(reply,d.web_sources||[])||`<p>${esc(reply)}</p>`}</div><small>${esc(d.status||'completed')} · ${fmtMs(d.latencyMs||d.latency_ms)}</small></article>`}catch(e){out.innerHTML=`<div class="v7-error"><strong>La tarea no pudo completarse.</strong><span>${esc(e.message||e)}</span></div>`}finally{state.busy=false;if(btn){btn.disabled=false;btn.textContent='Ejecutar tarea'}}}

  document.addEventListener('click',event=>{
    const nav=event.target?.closest?.('.nav-list button[data-view]');
    if(nav){event.preventDefault();event.stopImmediatePropagation();openPanel(nav.dataset.view);return}
    const view=event.target?.closest?.('[data-v7-view]');if(view){openPanel(view.dataset.v7View);return}
    const agent=event.target?.closest?.('[data-agent]');if(agent){const id=agent.dataset.agent;localStorage.setItem('wae.mode',id);const matching=$(`.capability-card[data-mode="${CSS.escape(id)}"]`);if(matching)matching.click();else{const pill=$('#modePill');if(pill)pill.textContent=agent.querySelector('strong')?.textContent||id}window.toast?.('Especialidad activada');closePanel();$('#messageInput')?.focus();return}
    const act=event.target?.closest?.('[data-v7-action]')?.dataset.v7Action;
    if(act==='new-chat'){localStorage.removeItem('iu.conversationId');$('#newChatBtn')?.click();closePanel();return}
    if(act==='workspace'){$('#workspaceBtn')?.click();closePanel();return}
    if(act==='attach'){$('#fileInput')?.click();return}
    if(act==='clear-files'){window.__waeRuntimeAttachments=[];renderKnowledge();window.toast?.('Adjuntos limpiados');return}
    if(act==='toggle-voice'){window.__waeVoice?.toggle?.().then(()=>renderComms());return}
    if(act==='stop-voice'){window.__waeVoice?.stop?.();return}
    const use=event.target?.closest?.('[data-project-use]');if(use){useProject(Number(use.dataset.projectUse));return}
    const del=event.target?.closest?.('[data-project-delete]');if(del){const list=localProjects();list.splice(Number(del.dataset.projectDelete),1);saveProjects(list);renderProjects();return}
    if(event.target?.id==='v7AddProject'){const title=$('#v7ProjectTitle')?.value.trim(),goal=$('#v7ProjectGoal')?.value.trim();if(!title||!goal)return;const list=localProjects();list.unshift({title,goal,createdAt:new Date().toISOString()});saveProjects(list);renderProjects();return}
    if(event.target?.id==='v7RunTask'){runTask();return}
  },true);

  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#universalPanel')?.classList.contains('open'))closePanel()});
  document.addEventListener('change',e=>{if(e.target?.id==='fileInput'&&state.view==='knowledge'&&$('#universalPanel')?.classList.contains('open'))setTimeout(renderKnowledge,80)});
  window.addEventListener('wae:stream-event',()=>{if(state.view==='control'&&$('#universalPanel')?.classList.contains('open'))setTimeout(()=>renderControl(false),60)});
  document.documentElement.classList.add('v7-dynamic-core');
})();