(()=>{
'use strict';
if(window.__ucPremium118)return;
const VERSION='118';
const $=(s,r=document)=>r.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const css=document.createElement('style');
css.textContent='#ucBenchmark118{position:fixed;inset:0;z-index:2147483000;display:none;background:rgba(3,6,5,.76);backdrop-filter:blur(12px);padding:18px;box-sizing:border-box}#ucBenchmark118.open{display:flex;align-items:center;justify-content:center}.uc118-card{width:min(980px,100%);max-height:88dvh;overflow:auto;border:1px solid rgba(40,247,164,.2);border-radius:22px;background:#09100d;color:#edf7f1;box-shadow:0 24px 80px rgba(0,0,0,.45)}.uc118-head{display:flex;align-items:center;justify-content:space-between;padding:20px 22px;border-bottom:1px solid rgba(255,255,255,.08);position:sticky;top:0;background:#09100d;z-index:2}.uc118-head h2{margin:0;font-size:1.05rem}.uc118-head p{margin:5px 0 0;color:#91a89e;font-size:.78rem}.uc118-close{border:0;background:transparent;color:#b9c8c1;font-size:1.4rem;cursor:pointer}.uc118-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;padding:16px 22px}.uc118-kpi{padding:13px;border-radius:14px;background:#0d1713;border:1px solid rgba(255,255,255,.06)}.uc118-kpi strong{display:block;font-size:1.15rem}.uc118-kpi span{color:#82978e;font-size:.7rem;text-transform:uppercase;letter-spacing:.08em}.uc118-table{width:100%;border-collapse:collapse;font-size:.78rem}.uc118-table th,.uc118-table td{text-align:left;padding:11px 22px;border-top:1px solid rgba(255,255,255,.06);vertical-align:top}.uc118-table th{color:#71877d;font-size:.67rem;text-transform:uppercase;letter-spacing:.07em}.uc118-ref{font-variant-numeric:tabular-nums;font-weight:800}.uc118-state{font-size:.68rem;font-weight:800;padding:4px 7px;border-radius:999px;background:#151d19;color:#a9bbb3}.uc118-note{margin:0 22px 20px;padding:12px 14px;border-radius:12px;background:#0d1713;color:#91a89e;font-size:.74rem;line-height:1.45}.uc118-actions{padding:0 22px 20px;display:flex;gap:8px}.uc118-actions button{border:1px solid rgba(40,247,164,.2);border-radius:10px;background:#0d1713;color:#dcebe4;padding:9px 12px;cursor:pointer}@media(max-width:620px){.uc118-summary{grid-template-columns:1fr}.uc118-table th:nth-child(3),.uc118-table td:nth-child(3){display:none}}';
document.head.appendChild(css);
const root=document.createElement('div');root.id='ucBenchmark118';root.innerHTML='<section class="uc118-card" role="dialog" aria-modal="true" aria-labelledby="uc118Title"><header class="uc118-head"><div><h2 id="uc118Title">Universal Core · Benchmark Arena</h2><p>Control objetivo contra referencias públicas de GPT-6 Astra.</p></div><button class="uc118-close" aria-label="Cerrar">×</button></header><div class="uc118-summary"></div><div class="uc118-body"></div><p class="uc118-note">Las referencias públicas no demuestran superioridad por sí solas. Para una comparación válida, Universal Core debe ejecutarse bajo el mismo protocolo, versión del conjunto de pruebas y condiciones. No se simulan resultados de Astra.</p><div class="uc118-actions"><button data-refresh>Actualizar</button><button data-open>Abrir endpoint</button></div></section>';
document.body.appendChild(root);
const body=$('.uc118-body',root),summary=$('.uc118-summary',root);
async function load(){body.innerHTML='<p style="padding:22px;color:#91a89e">Cargando contrato de benchmark…</p>';try{const r=await fetch('/api/benchmark/astra-regression',{cache:'no-store'});if(!r.ok)throw new Error('benchmark_http_'+r.status);const data=await r.json(),tasks=Array.isArray(data.tasks)?data.tasks:[],s=data.summary||{};summary.innerHTML='<div class="uc118-kpi"><strong>'+tasks.length+'</strong><span>métricas</span></div><div class="uc118-kpi"><strong>'+Number(s.p1||0)+'</strong><span>sin medición</span></div><div class="uc118-kpi"><strong>HOLD</strong><span>certificación global</span></div>';body.innerHTML='<table class="uc118-table"><thead><tr><th>Protocolo</th><th>Referencia Astra</th><th>Estado</th></tr></thead><tbody>'+tasks.map(t=>'<tr><td><strong>'+esc(t.protocol)+'</strong><br><span style="color:#6f8379">'+esc(t.metricId)+'</span></td><td class="uc118-ref">'+(Number(t.target)*100).toFixed(1)+'%</td><td><span class="uc118-state">'+esc(t.status)+'</span></td></tr>').join('')+'</tbody></table>';}catch(e){summary.innerHTML='';body.innerHTML='<p style="padding:22px;color:#d4a7a7">Benchmark no disponible en este momento.</p>';}}
function open(){root.classList.add('open');load()}function close(){root.classList.remove('open')}
$('.uc118-close',root).onclick=close;root.addEventListener('click',e=>{if(e.target===root)close()});$('[data-refresh]',root).onclick=load;$('[data-open]',root).onclick=()=>window.open('/api/benchmark/astra-regression','_blank','noopener');document.addEventListener('click',e=>{if(e.target.closest('#benchmarkBtn'))open()});window.__ucPremium118={version:VERSION,open,close,refresh:load};
})();