(()=>{
  const U='https://pbswcbryxawsmltyromd.supabase.co',K='sb_publishable_2zXa35U9Z--xuy_mQekG9w_kY7AVlv-',E=`${U}/functions/v1/wae-local-voice-demo-v61`;
  const SID='iu.sessionId',SECRET='iu.sessionSecret',CID='iu.conversationId';
  localStorage.setItem('wae.endpoint','/api/chat');window.__waeRuntimeAttachments=[];
  const edge=async p=>{const r=await fetch(E,{method:'POST',headers:{'content-type':'application/json','apikey':K,'x-client-info':'wae-runtime-bootstrap/1.6'},body:JSON.stringify(p),cache:'no-store'}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d};
  let boot;const bootstrap=()=>boot||(boot=edge({action:'bootstrap',session_id:localStorage.getItem(SID)||'',session_secret:localStorage.getItem(SECRET)||''}).then(d=>{if(!d.session_id||!d.session_secret)throw new Error('invalid_bootstrap');localStorage.setItem(SID,d.session_id);localStorage.setItem(SECRET,d.session_secret);return d}).catch(e=>{boot=null;throw e}));
  const auth=()=>({session_id:localStorage.getItem(SID)||'',session_secret:localStorage.getItem(SECRET)||''});
  const esc=t=>String(t??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function card(d){const e=document.querySelector('.v2-runtime-copy');if(!e)return;if(d.model_count!==undefined)e.innerHTML=`<strong>Adaptive Runtime · ${d.model_count} modelos</strong><small>${d.streaming?'streaming · ':''}${d.ttft?'TTFT · ':''}${d.adaptive_routing?'routing adaptativo':''}</small>`;else if(d.model)e.innerHTML=`<strong>${esc(d.model)}</strong><small>${esc(d.routing_path||'')} · ${Number(d.ttft_ms||0)}ms TTFT · ${Number(d.latency_ms||0)}ms total</small>`}
  async function files(list){const ok=/\.(txt|md|markdown|json|csv|tsv|js|mjs|cjs|ts|tsx|jsx|css|html|htm|xml|yaml|yml|py|java|go|rs|sql|sh|log)$/i,out=[];for(const f of [...list].slice(0,5)){if(!(f.type.startsWith('text/')||f.type.includes('json')||f.type.includes('xml')||ok.test(f.name)))continue;out.push({name:f.name,type:f.type||'text/plain',text:(await f.text()).slice(0,120000)})}window.__waeRuntimeAttachments=out;window.toast?.(out.length?`${out.length} archivo${out.length===1?'':'s'} listo${out.length===1?'':'s'}`:'Formato todavía no procesable como texto')}
  function styles(){if(document.querySelector('#iuHistoryStyles'))return;const s=document.createElement('style');s.id='iuHistoryStyles';s.textContent='.iu-history{margin:4px 14px 12px;display:grid;gap:5px}.iu-history-title{padding:7px;color:#5e6165;font-size:.56rem;font-weight:800;letter-spacing:.12em}.iu-history button{border:0;background:transparent;color:#a5aaad;text-align:left;border-radius:11px;padding:9px 10px;display:grid;gap:4px;cursor:pointer;min-width:0}.iu-history button:hover,.iu-history button.active{background:#17191d;color:#f4f7f6}.iu-history strong{font-size:.7rem;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.iu-history small{font-size:.56rem;color:#62666a}';document.head.appendChild(s)}
  async function history(){await bootstrap();styles();const d=await edge({action:'list_conversations',...auth()}),drawer=document.querySelector('#drawer');if(!drawer)return;let box=drawer.querySelector('.iu-history');if(!box){box=document.createElement('section');box.className='iu-history';drawer.querySelector('.nav-label')?.before(box)}box.innerHTML='<div class="iu-history-title">CONVERSACIONES</div>';for(const c of (d.conversations||[]).slice(0,8)){const b=document.createElement('button');b.type='button';b.classList.toggle('active',c.id===localStorage.getItem(CID));b.innerHTML=`<strong>${esc(c.title||'Conversación')}</strong><small>${esc(c.mode||'general')} · ${new Date(c.updated_at).toLocaleDateString('es-MX',{day:'2-digit',month:'short'})}</small>`;b.onclick=async()=>{const x=await edge({action:'get_conversation',...auth(),conversation_id:c.id});localStorage.setItem(CID,c.id);const fmt=new Intl.DateTimeFormat('es-MX',{hour:'2-digit',minute:'2-digit'});localStorage.setItem('wae.messages',JSON.stringify((x.messages||[]).filter(m=>['user','assistant'].includes(m.role)).map(m=>({role:m.role,text:m.content,at:m.created_at?fmt.format(new Date(m.created_at)):''})).slice(-60)));location.reload()};box.appendChild(b)}}
  const newChat=()=>{localStorage.removeItem(CID);window.__waeRuntimeAttachments=[]};
  document.addEventListener('DOMContentLoaded',()=>{document.querySelector('#fileInput')?.addEventListener('change',e=>files(e.target.files));document.querySelector('#newChatBtn')?.addEventListener('click',newChat,true);document.querySelector('#drawerNewChat')?.addEventListener('click',newChat,true);const ep=document.querySelector('#apiEndpoint');if(ep){ep.value='/api/chat';ep.disabled=true}bootstrap().then(()=>Promise.allSettled([edge({action:'health'}).then(card),history()])).catch(()=>{});import('./streaming-v1.js').catch(e=>console.warn('[WAE stream loader]',e))});
  window.__iuRuntime={edge,bootstrap,auth,history,card};
})();
