(()=>{
  const SUPABASE_URL='https://pbswcbryxawsmltyromd.supabase.co';
  const SUPABASE_KEY='sb_publishable_2zXa35U9Z--xuy_mQekG9w_kY7AVlv-';
  const VOICE_ENDPOINT=`${SUPABASE_URL}/functions/v1/wae-natural-voice-v60`;
  const TELEMETRY_ENDPOINT=`${SUPABASE_URL}/rest/v1/rpc/iu_record_client_telemetry`;
  const SID='iu.sessionId',SECRET='iu.sessionSecret',VOICE_ENABLED='iu.voiceEnabled',VOICE_NAME='iu.voiceName',LEGACY='wae.autoVoice';
  let enabled=localStorage.getItem(VOICE_ENABLED)!=='false',voice=localStorage.getItem(VOICE_NAME)||'Kore',context=null,currentSource=null,currentAudio=null,currentUtterance=null,runId=0,queue=[],queueRunning=false,cloudBackoffUntil=0,lastEngine='idle';
  const toast=m=>window.toast?.(m),session=()=>({session_id:localStorage.getItem(SID)||'',session_secret:localStorage.getItem(SECRET)||''}),cleanChunk=t=>String(t||'').trim();
  localStorage.setItem(LEGACY,String(enabled));

  function emitState(state,engine=lastEngine,error=null){lastEngine=engine||lastEngine;document.documentElement.dataset.voiceState=state;document.documentElement.dataset.voiceEngine=lastEngine;document.documentElement.dataset.voicePlaying=state==='playing'?'true':'false';window.dispatchEvent(new CustomEvent('wae:voice-state',{detail:{state,engine:lastEngine,error,enabled}}))}
  function chunks(text,max=3400){text=cleanChunk(text);if(!text)return[];const parts=text.split(/(?<=[.!?])\s+(?=[A-ZÁÉÍÓÚÑ0-9])/u),out=[];let buf='';for(const part of parts){if(part.length>max){if(buf){out.push(buf);buf=''}for(let i=0;i<part.length;i+=max)out.push(part.slice(i,i+max));continue}if((buf+' '+part).trim().length>max){out.push(buf);buf=part}else buf=(buf+' '+part).trim()}if(buf)out.push(buf);return out}
  function browserText(raw){return String(raw||'').normalize('NFKC').replace(/```[\s\S]*?```/g,' ').replace(/:::progress\s+([^|\n]+)\|(\d+(?:\.\d+)?)/gi,'$1, $2 por ciento.').replace(/:::metric\s+([^|\n]+)\|([^|\n]+)(?:\|[^\n]+)?/gi,'$1, $2.').replace(/!\[[^\]]*\]\([^)]*\)/g,' ').replace(/\[([^\]]+)\]\([^)]*\)/g,'$1').replace(/\[(?:W|M)\d+\]/gi,' ').replace(/https?:\/\/\S+|www\.\S+/gi,' enlace disponible ').replace(/<[^>]+>/g,' ').replace(/(^|\n)\s{0,3}#{1,6}\s*/g,'$1').replace(/(^|\n)\s*(?:[-+*•▪◦●○■□◆◇►▶]|\d+[.)])\s+/gu,'$1').replace(/\*\*|__|~~|[*_~`]/g,'').replace(/[→⇒➜➝➞➡⟶⟹↦↪]/gu,', ').replace(/[•▪◦●○■□◆◇►▶]/gu,', ').replace(/\|/g,', ').replace(/[#@]/g,' ').replace(/[\p{Extended_Pictographic}\uFE0F\u200D]/gu,'').replace(/[\[\]{}<>]/g,' ').replace(/\b(\d+(?:[.,]\d+)?)\s*%/g,'$1 por ciento').replace(/[ \t]+/g,' ').replace(/\s*\n\s*/g,'. ').replace(/(?:\.\s*){2,}/g,'. ').replace(/\s+([,.!?;:])/g,'$1').replace(/([,.!?;:])(?=[\p{L}\p{N}])/gu,'$1 ').replace(/\s+/g,' ').trim()}
  function getContext(){if(context)return context;const AC=window.AudioContext||window.webkitAudioContext;if(AC)context=new AC({latencyHint:'interactive'});return context}
  async function unlock(){try{const c=getContext();if(c?.state==='suspended')await c.resume();if('speechSynthesis'in window)void speechSynthesis.getVoices();return true}catch{return false}}
  function stop(){runId++;queue.length=0;queueRunning=false;try{currentSource?.stop()}catch{}currentSource=null;if(currentAudio){currentAudio.pause();currentAudio.src='';currentAudio=null}if('speechSynthesis'in window){try{speechSynthesis.cancel()}catch{}}currentUtterance=null;emitState(enabled?'ready':'disabled','idle')}
  function prepareQueue(){stop();queue=[];return runId}
  async function recordTelemetry(status,started,error=null,metadata={}){const s=session();if(!s.session_id||!s.session_secret)return;try{await fetch(TELEMETRY_ENDPOINT,{method:'POST',headers:{'content-type':'application/json','apikey':SUPABASE_KEY},body:JSON.stringify({p_session_id:s.session_id,p_session_secret:s.session_secret,p_kind:'tts',p_status:status,p_latency_ms:Math.max(0,Date.now()-started),p_error_code:error?String(error).slice(0,160):null,p_metadata:{voice,client:'wae-natural-voice-client/2.0',engine:lastEngine,...metadata}}),cache:'no-store'})}catch{}}
  async function fetchAudio(text){if(Date.now()<cloudBackoffUntil)throw new Error('cloud_tts_backoff');const s=session();if(!s.session_id||!s.session_secret)throw new Error('voice_session_missing');const r=await fetch(VOICE_ENDPOINT,{method:'POST',headers:{'content-type':'application/json','apikey':SUPABASE_KEY,'x-client-info':'wae-inteligencia-universal-voice/2.0'},body:JSON.stringify({action:'speak',...s,text,voice}),cache:'no-store'});if(!r.ok){const d=await r.json().catch(()=>({}));const error=new Error(d.error||`voice_${r.status}`);error.status=r.status;throw error}return r.arrayBuffer()}
  async function playBuffer(buffer,myRun){const c=getContext();if(c){if(c.state==='suspended')await c.resume();const decoded=await c.decodeAudioData(buffer.slice(0));if(myRun!==runId)return;await new Promise((resolve,reject)=>{const src=c.createBufferSource();currentSource=src;src.buffer=decoded;src.connect(c.destination);src.onended=()=>{if(currentSource===src)currentSource=null;resolve()};try{src.start()}catch(e){reject(e)}});return}const blob=new Blob([buffer],{type:'audio/wav'}),url=URL.createObjectURL(blob);await new Promise((resolve,reject)=>{const a=new Audio(url);currentAudio=a;a.onended=()=>{URL.revokeObjectURL(url);if(currentAudio===a)currentAudio=null;resolve()};a.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('audio_playback_failed'))};a.play().catch(reject)})}
  function pickBrowserVoice(){if(!('speechSynthesis'in window))return null;const voices=speechSynthesis.getVoices()||[];const score=v=>{const lang=String(v.lang||'').replace('_','-').toLowerCase(),name=String(v.name||'').toLowerCase();let n=0;if(lang==='es-mx')n+=100;else if(lang.startsWith('es-419'))n+=90;else if(lang.startsWith('es-us'))n+=80;else if(lang.startsWith('es'))n+=70;if(/google|microsoft|natural|premium|enhanced|neural/.test(name))n+=15;if(v.localService)n+=3;return n};return voices.filter(v=>/^es/i.test(v.lang||'')).sort((a,b)=>score(b)-score(a))[0]||voices[0]||null}
  async function playBrowser(text,myRun){if(!('speechSynthesis'in window))throw new Error('browser_tts_unavailable');const clean=browserText(text);if(!clean)return;const pieces=chunks(clean,260);for(const part of pieces){if(myRun!==runId)return;await new Promise((resolve,reject)=>{const u=new SpeechSynthesisUtterance(part);currentUtterance=u;u.lang='es-MX';u.rate=.98;u.pitch=1;u.volume=1;const selected=pickBrowserVoice();if(selected)u.voice=selected;u.onend=()=>{if(currentUtterance===u)currentUtterance=null;resolve()};u.onerror=e=>reject(new Error(e?.error||'browser_tts_failed'));try{speechSynthesis.speak(u)}catch(e){reject(e)}})}}
  async function playText(text,myRun){try{const audio=await fetchAudio(text);if(myRun!==runId)return'cancelled';emitState('playing','cloud');await playBuffer(audio,myRun);return'cloud'}catch(e){console.warn('[Universal Core Voice cloud]',e?.message||e);cloudBackoffUntil=Date.now()+5*60*1000;emitState('fallback','browser',e?.message||String(e));await playBrowser(text,myRun);return'browser'}}
  async function speak(text,{force=false}={}){if(!force&&window.__iuSuppressNextAutoSpeech===true){window.__iuSuppressNextAutoSpeech=false;return false}if(!enabled&&!force)return false;stop();const myRun=runId,started=Date.now(),parts=chunks(browserText(text),900);if(!parts.length)return false;emitState('starting','cloud');let engine='cloud';try{await unlock();for(const chunk of parts){if(myRun!==runId){void recordTelemetry('cancelled',started,null,{chunks:parts.length,mode:'full'});return false}engine=await playText(chunk,myRun)||engine}void recordTelemetry('ok',started,null,{chunks:parts.length,characters:String(text||'').length,mode:'full',engine});return true}catch(e){console.warn('[Universal Core Voice]',e?.message||e);void recordTelemetry('error',started,e?.message||e,{chunks:parts.length,characters:String(text||'').length,mode:'full',engine});emitState('error',engine,e?.message||String(e));toast('No pude reproducir voz en este dispositivo');return false}finally{if(myRun===runId)emitState(enabled?'ready':'disabled',engine)}}
  async function pumpQueue(myRun,started){if(queueRunning)return true;queueRunning=true;let played=0,engine='cloud';emitState('starting','cloud');try{await unlock();while(myRun===runId&&queue.length){const part=queue.shift();if(!part)continue;engine=await playText(part,myRun)||engine;played++}if(myRun===runId)void recordTelemetry('ok',started,null,{chunks:played,mode:'progressive',engine});return myRun===runId}catch(e){console.warn('[Universal Core Voice queue]',e?.message||e);queue.length=0;void recordTelemetry('error',started,e?.message||e,{chunks:played,mode:'progressive',engine});emitState('error',engine,e?.message||String(e));return false}finally{queueRunning=false;if(myRun===runId)emitState(enabled?'ready':'disabled',engine)}}
  async function enqueue(text){if(!enabled)return false;const parts=chunks(browserText(text),260).filter(Boolean);if(!parts.length)return false;window.__iuSuppressNextAutoSpeech=true;queue.push(...parts);const myRun=runId;if(queueRunning)return true;return pumpQueue(myRun,Date.now())}
  async function setEnabled(value){enabled=!!value;localStorage.setItem(VOICE_ENABLED,String(enabled));localStorage.setItem(LEGACY,String(enabled));if(!enabled)stop();else emitState('ready','idle');const s=session();if(s.session_id&&s.session_secret){fetch(VOICE_ENDPOINT,{method:'POST',headers:{'content-type':'application/json','apikey':SUPABASE_KEY},body:JSON.stringify({action:'preferences',...s,set:{voice_enabled:enabled,voice_name:voice}}),cache:'no-store'}).catch(()=>{})}return enabled}
  async function toggle(){const value=await setEnabled(!enabled);toast(value?'Voz automática activada':'Voz automática desactivada');return value}
  async function setVoice(name){voice=String(name||'Kore');localStorage.setItem(VOICE_NAME,voice);return voice}
  function loadExperience(){if(!document.querySelector('link[data-wae-v5]')){const css=document.createElement('link');css.rel='stylesheet';css.href='./experience-v5.css';css.dataset.waeV5='true';document.head.appendChild(css)}if(!document.querySelector('script[data-wae-v5]')){const js=document.createElement('script');js.src='./experience-v5.js';js.defer=true;js.dataset.waeV5='true';document.head.appendChild(js)}}
  emitState(enabled?'ready':'disabled','idle');
  if('speechSynthesis'in window)speechSynthesis.addEventListener?.('voiceschanged',()=>emitState(enabled?'ready':'disabled',lastEngine));
  window.__waeVoice={speak,enqueue,prepareQueue,stop,toggle,unlock,setEnabled,setVoice,get enabled(){return enabled},get voice(){return voice},get queueLength(){return queue.length},get engine(){return lastEngine},get cloudBackoff(){return Math.max(0,cloudBackoffUntil-Date.now())}};
  loadExperience();
})();
