(()=>{
  const SUPABASE_URL='https://pbswcbryxawsmltyromd.supabase.co',SUPABASE_KEY='sb_publishable_2zXa35U9Z--xuy_mQekG9w_kY7AVlv-';
  const VOICE_ENDPOINT=`${SUPABASE_URL}/functions/v1/wae-natural-voice-v60`,TELEMETRY_ENDPOINT=`${SUPABASE_URL}/rest/v1/rpc/iu_record_client_telemetry`;
  const SID='iu.sessionId',SECRET='iu.sessionSecret',VOICE_ENABLED='iu.voiceEnabled',VOICE_NAME='iu.voiceName';
  if(localStorage.getItem(VOICE_ENABLED)===null)localStorage.setItem(VOICE_ENABLED,'true');
  let enabled=localStorage.getItem(VOICE_ENABLED)!=='false',voice=localStorage.getItem(VOICE_NAME)||'Kore',context=null,currentSource=null,currentAudio=null,utterance=null,runId=0,queue=[],queueRunning=false;
  const toast=m=>window.toast?.(m),session=()=>({session_id:localStorage.getItem(SID)||'',session_secret:localStorage.getItem(SECRET)||''}),clean=t=>String(t||'').trim();
  function chunks(text,max=3400){text=clean(text);if(!text)return[];const parts=text.split(/(?<=[.!?])\s+(?=[A-ZÁÉÍÓÚÑ0-9])/u),out=[];let b='';for(const p of parts){if((b+' '+p).trim().length>max){if(b)out.push(b);b=p}else b=(b+' '+p).trim()}if(b)out.push(b);return out.flatMap(x=>x.length<=max?[x]:Array.from({length:Math.ceil(x.length/max)},(_,i)=>x.slice(i*max,(i+1)*max)))}
  function getContext(){if(context)return context;const AC=window.AudioContext||window.webkitAudioContext;if(AC)context=new AC({latencyHint:'interactive'});return context}
  async function unlock(){try{const c=getContext();if(c?.state==='suspended')await c.resume();if('speechSynthesis'in window){speechSynthesis.resume();const u=new SpeechSynthesisUtterance('');u.volume=0;speechSynthesis.speak(u)}return true}catch{return false}}
  function stop(){runId++;queue.length=0;queueRunning=false;try{currentSource?.stop()}catch{}currentSource=null;if(currentAudio){currentAudio.pause();currentAudio.src='';currentAudio=null}if('speechSynthesis'in window)speechSynthesis.cancel();utterance=null;document.documentElement.dataset.voicePlaying='false'}
  function prepareQueue(){stop();queue=[];return runId}
  async function telemetry(status,started,error=null,metadata={}){const x=session();if(!x.session_id||!x.session_secret)return;try{await fetch(TELEMETRY_ENDPOINT,{method:'POST',headers:{'content-type':'application/json','apikey':SUPABASE_KEY},body:JSON.stringify({p_session_id:x.session_id,p_session_secret:x.session_secret,p_kind:'tts',p_status:status,p_latency_ms:Math.max(0,Date.now()-started),p_error_code:error?String(error).slice(0,160):null,p_metadata:{voice,client:'wae-voice-client/2.0',...metadata}}),cache:'no-store'})}catch{}}
  async function fetchAudio(text){const x=session();if(!x.session_id||!x.session_secret)throw new Error('voice_session_missing');const r=await fetch(VOICE_ENDPOINT,{method:'POST',headers:{'content-type':'application/json','apikey':SUPABASE_KEY,'x-client-info':'wae-inteligencia-universal-voice/2.0'},body:JSON.stringify({action:'speak',...x,text,voice}),cache:'no-store'});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d.error||`voice_${r.status}`)}return r.arrayBuffer()}
  async function playBuffer(buffer,myRun){const c=getContext();if(c){if(c.state==='suspended')await c.resume();const decoded=await c.decodeAudioData(buffer.slice(0));if(myRun!==runId)return;await new Promise((resolve,reject)=>{const src=c.createBufferSource();currentSource=src;src.buffer=decoded;src.connect(c.destination);src.onended=()=>{if(currentSource===src)currentSource=null;resolve()};try{src.start()}catch(e){reject(e)}});return}const url=URL.createObjectURL(new Blob([buffer],{type:'audio/wav'}));await new Promise((resolve,reject)=>{const a=new Audio(url);currentAudio=a;a.onended=()=>{URL.revokeObjectURL(url);currentAudio=null;resolve()};a.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('audio_playback_failed'))};a.play().catch(reject)})}
  function browserVoice(){const vs=speechSynthesis.getVoices?.()||[];return vs.find(v=>/^es-MX/i.test(v.lang))||vs.find(v=>/^es/i.test(v.lang))||vs.find(v=>/Spanish|Español/i.test(v.name))||vs[0]||null}
  async function speakBrowser(text,myRun){if(!('speechSynthesis'in window))throw new Error('browser_tts_unavailable');if(myRun!==runId)return false;speechSynthesis.cancel();await new Promise((resolve,reject)=>{const u=new SpeechSynthesisUtterance(clean(text));utterance=u;u.lang='es-MX';u.rate=.98;u.pitch=1;const v=browserVoice();if(v)u.voice=v;u.onend=()=>{utterance=null;resolve()};u.onerror=e=>reject(new Error(e.error||'browser_tts_failed'));speechSynthesis.speak(u)});return true}
  async function playText(text,myRun){try{const audio=await fetchAudio(text);await playBuffer(audio,myRun);return'cloud'}catch(cloudError){await speakBrowser(text,myRun);return'browser-fallback'}}
  async function speak(text,{force=false}={}){if(!force&&window.__iuSuppressNextAutoSpeech===true){window.__iuSuppressNextAutoSpeech=false;return false}if(!enabled&&!force)return false;stop();const myRun=runId,started=Date.now(),parts=chunks(text);if(!parts.length)return false;document.documentElement.dataset.voicePlaying='true';try{await unlock();let engine='cloud';for(const p of parts){if(myRun!==runId)return false;engine=await playText(p,myRun)}void telemetry('ok',started,null,{chunks:parts.length,engine,mode:'full'});return true}catch(e){console.warn('[Universal Core Voice]',e?.message||e);void telemetry('error',started,e?.message||e,{chunks:parts.length,mode:'full'});toast('No fue posible reproducir audio en este dispositivo');return false}finally{if(myRun===runId)document.documentElement.dataset.voicePlaying='false'}}
  async function pump(myRun,started){if(queueRunning)return true;queueRunning=true;document.documentElement.dataset.voicePlaying='true';let played=0,engine='cloud';try{await unlock();while(myRun===runId&&queue.length){const t=queue.shift();if(!t)continue;engine=await playText(t,myRun);played++}if(myRun===runId)void telemetry('ok',started,null,{chunks:played,engine,mode:'progressive'});return myRun===runId}catch(e){queue.length=0;void telemetry('error',started,e?.message||e,{chunks:played,mode:'progressive'});return false}finally{queueRunning=false;if(myRun===runId)document.documentElement.dataset.voicePlaying='false'}}
  async function enqueue(text){if(!enabled)return false;const parts=chunks(text,900).filter(Boolean);if(!parts.length)return false;window.__iuSuppressNextAutoSpeech=true;queue.push(...parts);const myRun=runId;return queueRunning||pump(myRun,Date.now())}
  async function setEnabled(v){enabled=!!v;localStorage.setItem(VOICE_ENABLED,String(enabled));if(!enabled)stop();return enabled}
  async function toggle(){await unlock();const v=await setEnabled(!enabled);toast(v?'Voz activada':'Voz desactivada');return v}
  async function setVoice(v){voice=String(v||'Kore');localStorage.setItem(VOICE_NAME,voice);return voice}
  document.addEventListener('pointerdown',()=>{if(enabled)unlock()}, {capture:true,once:true});
  window.__waeVoice={speak,enqueue,prepareQueue,stop,toggle,unlock,setEnabled,setVoice,get enabled(){return enabled},get voice(){return voice},get queueLength(){return queue.length}};
})();
