import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import capacityChatV77 from '../api/capacity-chat-v77.js';
import {GPU_FABRIC_VERSION,GPU_SCHEDULER_VERSION,gpuFabricSnapshot,rankGpuLanes,generateWithGpuFabric,__seedGpuLaneStatsForTests,__resetGpuFabricForTests,classifyGpuTask} from '../lib/gpu-fabric-v77.js';

const KEYS=['WAE_GPU_FABRIC_ENABLED','WAE_GPU_FABRIC_MAX_ATTEMPTS','WAE_GPU_FABRIC_TIMEOUT_MS','WAE_GPU_HEDGING_ENABLED','WAE_GPU_HEDGE_DELAY_MS','WAE_GPU_WEIGHT_RELIABILITY','WAE_GPU_WEIGHT_LATENCY','WAE_GPU_WEIGHT_RESPONSE_START','WAE_GPU_WEIGHT_COST','WAE_GPU_WEIGHT_QUALITY','WAE_GPU_WEIGHT_AFFINITY','WAE_GPU_WEIGHT_PRIORITY','NVIDIA_API_KEY','GROQ_API_KEY','HF_TOKEN','HUGGINGFACE_API_KEY','OPENROUTER_API_KEY',...Array.from({length:8},(_,i)=>i+1).flatMap(i=>[`WAE_GPU_LANE_${i}_ID`,`WAE_GPU_LANE_${i}_BASE_URL`,`WAE_GPU_LANE_${i}_API_KEY`,`WAE_GPU_LANE_${i}_MODEL`,`WAE_GPU_LANE_${i}_PRIORITY`,`WAE_GPU_LANE_${i}_COST_WEIGHT`,`WAE_GPU_LANE_${i}_QUALITY_HINT`,`WAE_GPU_LANE_${i}_SPECIALTIES`])];
function isolatedEnv(){const saved=new Map(KEYS.map(key=>[key,process.env[key]]));for(const key of KEYS)delete process.env[key];__resetGpuFabricForTests();return()=>{for(const[key,value]of saved){if(value===undefined)delete process.env[key];else process.env[key]=value}__resetGpuFabricForTests()}}
function custom(index,id,{model='test/model',priority=100,cost=1,quality=.65,specialties='general'}={}){const prefix=`WAE_GPU_LANE_${index}`;process.env[`${prefix}_ID`]=id;process.env[`${prefix}_BASE_URL`]=`https://${id}.example/v1`;process.env[`${prefix}_API_KEY`]=`secret-${id}`;process.env[`${prefix}_MODEL`]=model;process.env[`${prefix}_PRIORITY`]=String(priority);process.env[`${prefix}_COST_WEIGHT`]=String(cost);process.env[`${prefix}_QUALITY_HINT`]=String(quality);process.env[`${prefix}_SPECIALTIES`]=specialties}
function responseAfter(ms,body,signal){return new Promise((resolve,reject)=>{const timer=setTimeout(()=>resolve(new Response(JSON.stringify(body),{status:200,headers:{'content-type':'application/json'}})),ms);if(signal){const abort=()=>{clearTimeout(timer);reject(signal.reason||new DOMException('Aborted','AbortError'))};if(signal.aborted)abort();else signal.addEventListener('abort',abort,{once:true})}})}

test('v77 exposes adaptive scheduling without inventing prices, TTFT or physical GPU counts',()=>{const restore=isolatedEnv();try{custom(1,'alpha');const snap=gpuFabricSnapshot();assert.equal(snap.version,GPU_FABRIC_VERSION);assert.equal(snap.schedulerVersion,GPU_SCHEDULER_VERSION);assert.equal(snap.strategy,'adaptive-utility-scheduler+delayed-hedging');assert.equal(snap.physicalGpuOwnership,false);assert.equal(snap.verifiedGpuCount,null);assert.match(snap.costPolicy,/Relative configurable routing weights/i);assert.match(snap.latencyPolicy,/not claimed as token TTFT/i);assert.doesNotMatch(JSON.stringify(snap),/secret-alpha/)}finally{restore()}});

test('scheduler ranks observed reliability and latency ahead of static priority when evidence is strong',()=>{const restore=isolatedEnv();try{custom(1,'legacy_fast',{priority:1,cost:1,quality:.65,specialties:'analysis'});custom(2,'proven_lane',{priority:90,cost:1,quality:.65,specialties:'analysis'});__seedGpuLaneStatsForTests('legacy_fast',{attempts:20,successes:8,failures:12,ewmaLatencyMs:6500,ewmaResponseStartMs:2200});__seedGpuLaneStatsForTests('proven_lane',{attempts:20,successes:20,failures:0,ewmaLatencyMs:900,ewmaResponseStartMs:180});const ranked=rankGpuLanes({message:'Analiza esta arquitectura y compara riesgos',mode:'analysis'});assert.equal(ranked[0].row.id,'proven_lane');assert.ok(ranked[0].decision.score<ranked[1].decision.score);assert.equal(ranked[0].decision.task,'analysis')}finally{restore()}});

test('task classifier separates code, executive, analysis, design and general turns',()=>{assert.equal(classifyGpuTask({message:'Corrige este bug de TypeScript'}),'code');assert.equal(classifyGpuTask({message:'Define estrategia de ROI para la empresa'}),'executive');assert.equal(classifyGpuTask({message:'Analiza riesgos de esta arquitectura'}),'analysis');assert.equal(classifyGpuTask({message:'Mejora el diseño UX de la interfaz'}),'design');assert.equal(classifyGpuTask({message:'Hola, ¿cómo estás?'}),'general')});

test('delayed hedging starts a second healthy lane only after the primary exceeds the hedge window',async()=>{const restore=isolatedEnv(),originalFetch=global.fetch;try{custom(1,'slow_primary',{priority:1,specialties:'analysis'});custom(2,'fast_hedge',{priority:2,specialties:'analysis'});process.env.WAE_GPU_FABRIC_MAX_ATTEMPTS='2';process.env.WAE_GPU_HEDGING_ENABLED='1';process.env.WAE_GPU_HEDGE_DELAY_MS='100';const calls=[];global.fetch=async(url,init={})=>{const text=String(url);calls.push({text,at:Date.now()});if(text.includes('slow_primary'))return responseAfter(450,{id:'slow',choices:[{message:{content:'lento'}}]},init.signal);return responseAfter(25,{id:'fast',choices:[{message:{content:'respuesta rápida válida'}}]},init.signal)};const started=Date.now(),result=await generateWithGpuFabric({system:'Sistema',message:'Analiza riesgos de esta arquitectura',mode:'analysis',history:[]});assert.equal(result.gpuLane,'fast_hedge');assert.equal(result.scheduler.mode,'delayed-hedged');assert.equal(result.scheduler.winner,'fast_hedge');assert.equal(result.text,'respuesta rápida válida');assert.equal(calls.length,2);assert.ok(calls[1].at-calls[0].at>=90);assert.ok(Date.now()-started<350)}finally{global.fetch=originalFetch;restore()}});

test('general turns stay single-lane and v77 remains wrapped through v84, v83 and v81 around v63 security/control',async()=>{const restore=isolatedEnv(),originalFetch=global.fetch;try{custom(1,'one',{priority:1});custom(2,'two',{priority:2});process.env.WAE_GPU_FABRIC_MAX_ATTEMPTS='2';process.env.WAE_GPU_HEDGING_ENABLED='1';let calls=0;global.fetch=async()=>{calls++;return new Response(JSON.stringify({choices:[{message:{content:'ok'}}]}),{status:200,headers:{'content-type':'application/json'}})};const result=await generateWithGpuFabric({system:'Sistema',message:'Hola',mode:'general'});assert.equal(result.scheduler.mode,'adaptive-sequential');assert.equal(calls,1);assert.equal(typeof capacityChatV77,'function');const alias=await readFile(new URL('../api/capacity-chat-v60.js',import.meta.url),'utf8'),resilienceWrapper=await readFile(new URL('../api/capacity-chat-v84.js',import.meta.url),'utf8'),factualWrapper=await readFile(new URL('../api/capacity-chat-v83.js',import.meta.url),'utf8'),recoveryWrapper=await readFile(new URL('../api/capacity-chat-v82.js',import.meta.url),'utf8'),healthWrapper=await readFile(new URL('../api/capacity-chat-v81.js',import.meta.url),'utf8'),wrapper=await readFile(new URL('../api/capacity-chat-v77.js',import.meta.url),'utf8'),caps=await readFile(new URL('../api/capabilities.js',import.meta.url),'utf8');assert.match(alias,/capacity-chat-v84\.js/);assert.match(resilienceWrapper,/capacity-chat-v83\.js/);assert.match(resilienceWrapper,/callIaGratisChat/);assert.match(factualWrapper,/capacity-chat-v81\.js/);assert.match(factualWrapper,/runFocusedFactualAnswer/);assert.match(recoveryWrapper,/capacity-chat-v81\.js/);assert.match(recoveryWrapper,/runKnowledgeAnswer/);assert.match(healthWrapper,/capacity-chat-v77\.js/);assert.match(healthWrapper,/chooseOperationalProvider/);assert.match(healthWrapper,/terminalControlFailure/);assert.match(wrapper,/capacityChatV63/);assert.match(wrapper,/sensitiveRequest/);assert.match(wrapper,/requiresGroundedData/);assert.match(wrapper,/originAllowed/);assert.match(wrapper,/allowRequest/);assert.match(caps,/gpu-fabric-v77\.js/)}finally{global.fetch=originalFetch;restore()}});