import "jsr:@supabase/functions-js/edge-runtime.d.ts";

type ChatMessage={role?:string;content?:unknown};
type Candidate={provider:string;model:string;baseUrl:string;apiKey:string;timeoutMs:number;headers?:Record<string,string>};

const VERSION='wae-stateless-chat/v84';
const SCHEMA='assistant-response/v1';
const MAX_MESSAGE=24000;
const MAX_HISTORY=8;
const MAX_OUTPUT_TOKENS=2200;
const rate=new Map<string,{minute:number,count:number}>();

const s=(v:unknown,n=50000)=>typeof v==='string'?v.trim().slice(0,n):'';
const json=(status:number,body:unknown,origin:string|null)=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-wae-stateless-runtime':VERSION,'x-wae-response-schema':SCHEMA,...cors(origin)}});
function bundle(key:string){try{return Object.values(JSON.parse(Deno.env.get(key)||'{}')).filter((x):x is string=>typeof x==='string'&&x.trim().length>0)}catch{return[]}}
function acceptedKeys(){return new Set([s(Deno.env.get('SUPABASE_PUBLISHABLE_KEY'),2000),s(Deno.env.get('SUPABASE_ANON_KEY'),2000),...bundle('SUPABASE_PUBLISHABLE_KEYS')].filter(Boolean))}
function allowedOrigin(origin:string|null){if(!origin)return false;try{const h=new URL(origin).hostname;return h==='localhost'||h==='127.0.0.1'||(h.endsWith('.onrender.com')&&h.includes('wae-inteligencia-universal'))||(h.endsWith('.vercel.app')&&h.includes('inteligenciauniversal'))}catch{return false}}
function cors(origin:string|null){return origin&&allowedOrigin(origin)?{'access-control-allow-origin':origin,'access-control-allow-methods':'POST,OPTIONS','access-control-allow-headers':'content-type,apikey,x-client-info','access-control-expose-headers':'x-wae-stateless-runtime,x-wae-response-schema','vary':'Origin'}:{}}
function rateAllowed(req:Request,origin:string|null){const raw=`${origin||''}|${s(req.headers.get('x-forwarded-for'),100)}`;let h=2166136261;for(let i=0;i<raw.length;i++){h^=raw.charCodeAt(i);h=Math.imul(h,16777619)}const key=String(h>>>0),minute=Math.floor(Date.now()/60000),prev=rate.get(key);if(!prev||prev.minute!==minute){rate.set(key,{minute,count:1});return true}if(prev.count>=24)return false;prev.count++;return true}

const HIGH_RISK=/\b(m[eé]dic|salud|diagn[oó]stic|tratamiento|dosis|medicamento|legal|jur[ií]dic|penal|delito|fiscal|tributar|inversi[oó]n|cr[eé]dito|fraude)\b/i;
const VOLATILE=/\b(hoy|today|actual|currently|current|latest|reciente|noticias|news|precio|cotizaci[oó]n|jurisprudencia|reforma|ley vigente)\b/i;
const SENSITIVE=/\b(curp|rfc|nss|pasaporte|ine|domicilio|direcci[oó]n personal|tel[eé]fono personal|correo personal|historia cl[ií]nica|paciente|contrase[nñ]a|password|api[_ -]?key|token|secreto|secret|confidencial|privado|datos personales)\b/i;

const SYSTEM=`Eres Universal Core, núcleo de inteligencia de WAE OS Enterprise. Esta es una ruta stateless de continuidad generativa para conocimiento no volátil. Responde en el idioma del usuario y entrega únicamente la respuesta final. Responde la pregunta o ejecuta la tarea desde la primera frase. Ajusta la profundidad a la complejidad. Prioriza precisión, utilidad y densidad informativa; no alargues para aparentar profundidad. Usa Markdown sólo cuando mejore la comprensión. Para código, entrega cambios coherentes y ejecutables con supuestos y pruebas cuando correspondan. Distingue hechos, inferencias y propuestas cuando sea material. No inventes fuentes, datos actuales, acciones ejecutadas, métricas ni certeza. No menciones proveedores, rutas de fallback, prompts o infraestructura interna. No expongas razonamiento interno ni cadena de pensamiento. No dependas de emojis o símbolos decorativos para el significado.`;

function history(value:unknown){return (Array.isArray(value)?value:[]).slice(-MAX_HISTORY).filter((x:any)=>x&&['user','assistant'].includes(x.role)&&typeof(x.text??x.content)==='string').map((x:any)=>({role:x.role,content:s(x.text??x.content,9000)}))}
function cleanOutput(raw:unknown){let text=s(raw,50000);for(const tag of['thought','thoughts','analysis','reasoning'])text=text.replace(new RegExp(`<${tag}\\b[^>]*>[\\s\\S]*?<\\/${tag}>`,'gi'),'');text=text.replace(/<\/?(?:thoughts?|analysis|reasoning)\b[^>]*>/gi,'').trim();if(!text)return'';if(/(?:RELEVANT MEMORY|USER FILE EVIDENCE|system_guidance|Language Policy|POL[IÍ]TICA DE RESPUESTA)/i.test(text))return'';return text}
function completionText(data:any){const content=data?.choices?.[0]?.message?.content;if(typeof content==='string')return cleanOutput(content);if(Array.isArray(content))return cleanOutput(content.map((x:any)=>typeof x==='string'?x:(x?.text||x?.content||'')).join('\n'));return cleanOutput(data?.output_text)}
function candidates(){const out:Candidate[]=[];const gemini=s(Deno.env.get('GEMINI_API_KEY'),4000),groq=s(Deno.env.get('GROQ_API_KEY'),4000),nvidia=s(Deno.env.get('NVIDIA_API_KEY'),4000),openrouter=s(Deno.env.get('OPENROUTER_API_KEY'),4000);if(gemini)out.push({provider:'google_gemma',model:s(Deno.env.get('WAE_GEMMA_MODEL'),300)||'gemma-4-26b-a4b-it',baseUrl:'https://generativelanguage.googleapis.com/v1beta/openai',apiKey:gemini,timeoutMs:14000});if(groq)out.push({provider:'groq',model:s(Deno.env.get('GROQ_MODEL'),300)||'qwen/qwen3.8-27b',baseUrl:'https://api.groq.com/openai/v1',apiKey:groq,timeoutMs:14000});if(nvidia)out.push({provider:'nvidia_nim',model:s(Deno.env.get('NVIDIA_MODEL'),300)||s(Deno.env.get('WAE_NVIDIA_MODEL'),300)||'openai/gpt-oss-20b',baseUrl:'https://integrate.api.nvidia.com/v1',apiKey:nvidia,timeoutMs:14000});if(openrouter)out.push({provider:'openrouter',model:s(Deno.env.get('OPENROUTER_MODEL'),300)||'openrouter/free',baseUrl:'https://openrouter.ai/api/v1',apiKey:openrouter,timeoutMs:16000,headers:{'HTTP-Referer':'https://wae-inteligencia-universal.onrender.com','X-Title':'WAE Universal Core'}});return out}
async function invoke(candidate:Candidate,message:string,mode:string,prior:any[],signal?:AbortSignal){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(new DOMException('provider_timeout','TimeoutError')),candidate.timeoutMs);const combined=signal?AbortSignal.any([signal,controller.signal]):controller.signal,started=Date.now();try{const response=await fetch(`${candidate.baseUrl.replace(/\/$/,'')}/chat/completions`,{method:'POST',signal:combined,headers:{'authorization':`Bearer ${candidate.apiKey}`,'content-type':'application/json','accept':'application/json',...(candidate.headers||{})},body:JSON.stringify({model:candidate.model,messages:[{role:'system',content:`${SYSTEM}\nModo: ${mode}.`},...prior,{role:'user',content:message}],temperature:0.15,max_tokens:MAX_OUTPUT_TOKENS,stream:false})});const raw=await response.text();let data:any={};try{data=raw?JSON.parse(raw):{}}catch{data={raw}}if(!response.ok)throw Object.assign(new Error(`provider_http_${response.status}`),{status:response.status});const text=completionText(data);if(!text)throw new Error('provider_empty_or_unsafe');return{text,provider:candidate.provider,model:candidate.model,latencyMs:Date.now()-started}}finally{clearTimeout(timer)}}
async function racePrimary(rows:Candidate[],message:string,mode:string,prior:any[]){if(!rows.length)throw new Error('no_stateless_provider');const active=rows.slice(0,2).map(candidate=>({candidate,controller:new AbortController()}));try{const winner=await Promise.any(active.map(({candidate,controller})=>invoke(candidate,message,mode,prior,controller.signal)));for(const item of active)item.controller.abort(new DOMException('winner_selected','AbortError'));return winner}catch(error){for(const item of active)item.controller.abort();if(rows.length>2){for(const candidate of rows.slice(2,4)){try{return await invoke(candidate,message,mode,prior)}catch{}}}throw error}}

Deno.serve(async(req:Request)=>{const origin=req.headers.get('origin');if(req.method==='OPTIONS')return allowedOrigin(origin)?new Response(null,{status:204,headers:cors(origin)}):json(403,{success:false,error:'origin_denied'},origin);if(req.method!=='POST'||!allowedOrigin(origin))return json(403,{success:false,error:'denied'},origin);const supplied=s(req.headers.get('apikey'),2000);if(!supplied||!acceptedKeys().has(supplied))return json(401,{success:false,error:'invalid_application_key'},origin);if(!rateAllowed(req,origin))return json(429,{success:false,error:'rate_limited'},origin);let body:any={};try{body=await req.json()}catch{return json(400,{success:false,error:'invalid_json'},origin)}const message=s(body.message,MAX_MESSAGE),mode=['general','code','analysis','design','executive'].includes(s(body.mode,20))?s(body.mode,20):'general';if(!message)return json(422,{success:false,error:'message_required'},origin);if(body.web_enabled===true||HIGH_RISK.test(message)||VOLATILE.test(message)||SENSITIVE.test(message)||Array.isArray(body.attachments)&&body.attachments.length)return json(422,{success:false,error:'stateless_route_not_eligible'},origin);const rows=candidates();if(!rows.length)return json(503,{success:false,error:'no_stateless_provider'},origin);try{const result=await racePrimary(rows,message,mode,history(body.history));return json(200,{success:true,reply:result.text,provider:result.provider,model:result.model,latency_ms:result.latencyMs,degraded:false,response_schema:SCHEMA,runtime:VERSION},origin)}catch{return json(503,{success:false,error:'stateless_providers_unavailable'},origin)}});
