const txt=(v:any,n=50000)=>typeof v==='string'?v.trim().slice(0,n):'';
const norm=(v:any)=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim().replace(/\s+/g,' ');
const lastUser=(messages:any[])=>[...messages].reverse().find(x=>x?.role==='user')?.content?.toString()||'';
const full=(messages:any[])=>messages.map(x=>txt(x?.content,40000)).filter(Boolean).join('\n');

function capture(source:string,rx:RegExp){return source.match(rx)?.[1]?.trim().replace(/[\s,]+$/,'')||null}
function facts(source:string){const out:any={};const project=capture(source,/(?:\bproyecto\b|\bproject\b)\s*[:=]?\s*([^;\n.]+)/i),database=capture(source,/(?:\bbase\s+de\s+datos\b|\bdatabase\b)\s*[:=]?\s*([^;\n.]+)/i),region=capture(source,/(?:\bregi[oó]n\b|\bregion\b)\s*[:=]?\s*([^;\n.]+)/i),p95=capture(source,/(?:objetivo\s*)?\bP95\b\s*[:=]?\s*(\d+(?:[.,]\d+)?)\s*ms\b/i);if(project)out.project=project;if(database)out.database=database;if(region)out.region=region;if(p95)out.p95_target_ms=Number(p95.replace(',','.'));return out}
function schema(user:string){const block=user.match(/\{([^{}]{1,1600})\}/)?.[1]||'';return[...block.matchAll(/["']([^"']+)["']\s*:\s*(string|number|boolean|null|["'][^"']*["']|-?\d+(?:\.\d+)?)/gi)].map(m=>({key:m[1],type:['string','number','boolean','null'].includes(m[2].toLowerCase())?m[2].toLowerCase():'literal'}))}
function fileBlock(context:string){return context.match(/USER FILE EVIDENCE[^:]*:\n([\s\S]*?)(?=\n\nCurrent UTC date:|\n\nRELEVANT MEMORY|\n\nWEB EVIDENCE|$)/i)?.[1]?.trim()||''}
function instruction(line:string){return/\b(?:instruction to model|instructions? for (?:the )?model|ignore (?:all|any|the|previous|prior)|system prompt|developer message|assistant message|jailbreak|reveal (?:any )?(?:private )?memory|replace .+ with|set .+ to|follow (?:these|the following) instructions?|disregard (?:all|previous|prior))\b/i.test(line)}
function safeFile(raw:string){const safe:string[]=[];let blocked=false,injected=false;for(const source of raw.split(/\r?\n/)){const line=source.trimEnd();if(/^\s*\[FILE\d+\]/i.test(line)){blocked=false;continue}if(instruction(line)){injected=true;blocked=true;continue}if(blocked)continue;safe.push(line)}return{text:safe.join('\n').trim(),injected}}
function pairs(source:string){const out:any[]=[];for(const raw of source.split(/\r?\n/)){const line=raw.replace(/^\s*[-*•]\s*/,'').trim(),m=line.match(/^([^:=]{1,120})\s*[:=]\s*(.+)$/);if(m)out.push({label:norm(m[1]),value:m[2].trim()})}return out}
function best(key:string,rows:any[]){const wanted=norm(key.replace(/_/g,' ')),exact=rows.find(r=>r.label===wanted);if(exact)return exact.value;const tokens=wanted.split(' ').filter(x=>x.length>1);return rows.map(r=>({...r,score:tokens.filter(t=>new Set(r.label.split(' ')).has(t)).length/Math.max(1,tokens.length)})).filter(r=>r.score>=.75).sort((a,b)=>b.score-a.score)[0]?.value||null}
function coerce(value:any,type:string){if(value==null)return null;if(type==='number'){const m=String(value).replace(/,/g,'').match(/-?\d+(?:\.\d+)?/);const n=m?Number(m[0]):NaN;return Number.isFinite(n)?n:null}if(type==='boolean'){if(/^(?:true|yes|si|sí|1)$/i.test(String(value).trim()))return true;if(/^(?:false|no|0)$/i.test(String(value).trim()))return false;return null}if(type==='null')return null;return String(value).replace(/^["']|["']$/g,'').trim()}
function factFor(key:string,f:any){const k=norm(key).replace(/ /g,'_'),aliases:any={project:'project',proyecto:'project',project_name:'project',database:'database',db:'database',base_de_datos:'database',region:'region',p95_target_ms:'p95_target_ms',p95:'p95_target_ms',p95_ms:'p95_target_ms',latency_p95_ms:'p95_target_ms',objetivo_p95_ms:'p95_target_ms'};const c=aliases[k]||k;return Object.prototype.hasOwnProperty.call(f,c)?f[c]:null}
function structured(user:string,context:string,f:any){const fields=schema(user);if(!fields.length)return null;const raw=fileBlock(context),safe=safeFile(raw),rows=pairs(safe.text),out:any={};let resolved=0;for(const field of fields){const k=norm(field.key).replace(/ /g,'_');let value=factFor(field.key,f);if(['ignored_embedded_instruction','embedded_instruction_ignored','prompt_injection_detected','embedded_instruction_detected'].includes(k))value=safe.injected;else if(['leaked_private_memory','private_memory_leaked'].includes(k))value=false;else if(value==null&&raw)value=coerce(best(field.key,rows),field.type);if(value!==null&&value!==undefined)resolved++;out[field.key]=value??null}return resolved?JSON.stringify(out):null}
function arithmetic(user:string){const m=user.trim().match(/^(-?\d+(?:\.\d+)?)\s*([+\-*\/x×])\s*(-?\d+(?:\.\d+)?)\s*\??$/i);if(!m)return null;const a=Number(m[1]),b=Number(m[3]),op=m[2],r=op==='+'?a+b:op==='-'?a-b:op==='/'?(b===0?NaN:a/b):a*b;return Number.isFinite(r)?String(r):null}
function webEvidence(context:string){const section=context.split(/WEB EVIDENCE/i)[1]?.split(/USER FILE EVIDENCE|Current UTC date/i)[0]||'';const rows=[...section.matchAll(/\[(W\d+)\]\s*([^\n]+)\nURL:\s*(https?:\/\/\S+)\nSNIPPET:\s*([^\n]+)/gi)].slice(0,4);return rows.length?`Encontré evidencia verificable disponible:\n\n${rows.map(r=>`- [${r[1]}] **${r[2].trim()}** — ${r[4].trim()}`).join('\n')}`:null}
function memorySummary(context:string,f:any){if(!/RELEVANT MEMORY/i.test(context))return null;const entries=Object.entries(f);return entries.length?entries.map(([k,v])=>`- **${k}**: ${v}`).join('\n'):'Hay memoria privada disponible para esta sesión. Universal Core no expone el bloque bruto de memoria.'}

export function nativeContinuity(messages:any[]){const started=Date.now(),user=lastUser(messages),context=full(messages),f=facts(context);let answer='';if(/\b(?:responde|reply)\s+(?:solamente|solo|only)\s+(?:con\s+la\s+palabra\s+)?OK\b/i.test(user))answer='OK';if(!answer)answer=structured(user,context,f)||'';if(!answer)answer=arithmetic(user)||'';if(!answer&&/\b(recupera|recuerda|memoria|remember|recall)\b/i.test(user))answer=memorySummary(context,f)||'';if(!answer)answer=webEvidence(context)||'';if(!answer){const raw=fileBlock(context),safe=safeFile(raw);if(raw)answer=safe.text?`Conservo la evidencia factual del archivo en modo de continuidad:\n\n${safe.text.slice(0,2600)}`:'Detecté instrucciones incrustadas en el archivo y las bloqueé en modo de continuidad.'}if(!answer&&/^\s*(hola|hey|hello|buen(?:os|as)?\s+(?:d[ií]as|tardes|noches))\b/i.test(user))answer='Hola. Universal Core está operativo en modo de continuidad. Puedo trabajar con memoria, archivos, evidencia y operaciones deterministas mientras se recupera la capacidad generativa principal.';if(!answer)answer='Universal Core mantiene la solicitud en modo de continuidad. La conversación, la memoria y la evidencia están preservadas. No inventaré una respuesta generativa: puedo recuperar datos, analizar archivos estructurados, usar evidencia disponible y ejecutar operaciones deterministas.'}const chars=messages.reduce((n,m)=>n+String(m?.content||'').length,0);return{text:answer,ttft_ms:null,latency_ms:Math.max(1,Date.now()-started),input_tokens:Math.max(1,Math.ceil(chars/4)),output_tokens:Math.max(1,Math.ceil(answer.length/4)),streamed:false,provider_request_at:started,provider:'universal_core_native',model:'universal-core-native-v1',modelRow:{cost_profile:{input_per_million:0,output_per_million:0}}}}

export function nativeCoreModel(){return{provider:'universal_core_native',model_name:'universal-core-native-v1',enabled:true,access_tier:'LOCAL',priority:99,effective_health:'healthy',registry_health:'healthy',circuit_state:'CLOSED',consecutive_failures:0,reliability_score:100,ewma_latency_ms:5,ewma_ttft_ms:null,streaming_claimed:false,streaming_verified:false,context_window:65536,max_output_tokens:2200,reasoning_capable:false,tools_capable:false,vision_capable:false,structured_output_capable:true,cost_profile:{input_per_million:0,output_per_million:0},capabilities:{runtime:'edge_native',requires_api_key:false,text_generation:true,structured_output:true},specific:{quality_score:72,reliability_score:100}}}
