import { sanitizeWebText } from './security-v1.js';
export const WEB_SEARCH_PROVIDERS_VERSION='web-search-providers/v1.0.0';
const text=(v,max=4000)=>String(v??'').replace(/\u0000/g,'').replace(/\s+/g,' ').trim().slice(0,max);
const timeout=(ms=8000)=>AbortSignal.timeout(Math.max(500,Math.min(Number(ms)||8000,15000)));
function normalized({provider,title,url,snippet,publishedAt,author,publication,raw}){const clean=sanitizeWebText(snippet||'',5000);return{provider,title:text(title,800),url:text(url,2000),snippet:clean.text,publishedAt:publishedAt||null,author:author||null,publication:publication||null,retrievedAt:new Date().toISOString(),promptInjectionDetected:clean.injectionDetected,raw}}
async function tavilySearch(query,{limit=8,fetchImpl=fetch,timeoutMs=9000}={}){const key=process.env.TAVILY_API_KEY;if(!key)return{provider:'tavily',status:'not_configured',results:[]};const res=await fetchImpl('https://api.tavily.com/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({api_key:key,query:text(query,1000),search_depth:'advanced',max_results:Math.max(1,Math.min(Number(limit)||8,20)),include_answer:false,include_raw_content:false}),signal:timeout(timeoutMs)});if(!res.ok)throw Object.assign(new Error(`tavily_http_${res.status}`),{status:res.status});const data=await res.json();return{provider:'tavily',status:'healthy',results:(Array.isArray(data?.results)?data.results:[]).map(x=>normalized({provider:'tavily',title:x.title,url:x.url,snippet:x.content,publishedAt:x.published_date||null,raw:{score:x.score}}))}}
async function braveSearch(query,{limit=8,fetchImpl=fetch,timeoutMs=9000}={}){const key=process.env.BRAVE_SEARCH_API_KEY;if(!key)return{provider:'brave',status:'not_configured',results:[]};const url=new URL('https://api.search.brave.com/res/v1/web/search');url.searchParams.set('q',text(query,1000));url.searchParams.set('count',String(Math.max(1,Math.min(Number(limit)||8,20))));url.searchParams.set('safesearch','moderate');const res=await fetchImpl(url,{headers:{Accept:'application/json','X-Subscription-Token':key},signal:timeout(timeoutMs)});if(!res.ok)throw Object.assign(new Error(`brave_http_${res.status}`),{status:res.status});const data=await res.json();return{provider:'brave',status:'healthy',results:(Array.isArray(data?.web?.results)?data.web.results:[]).map(x=>normalized({provider:'brave',title:x.title,url:x.url,snippet:x.description,publishedAt:x.age||x.page_age||null,raw:{profile:x.profile?.long_name||null}}))}}
async function googleCustomSearch(query,{limit=8,fetchImpl=fetch,timeoutMs=9000}={}){const key=process.env.GOOGLE_CUSTOM_SEARCH_API_KEY,cx=process.env.GOOGLE_CUSTOM_SEARCH_ENGINE_ID;if(!key||!cx)return{provider:'google_custom_search',status:'not_configured_or_ineligible',results:[]};const url=new URL('https://www.googleapis.com/customsearch/v1');url.searchParams.set('key',key);url.searchParams.set('cx',cx);url.searchParams.set('q',text(query,1000));url.searchParams.set('num',String(Math.max(1,Math.min(Number(limit)||8,10))));const res=await fetchImpl(url,{headers:{Accept:'application/json'},signal:timeout(timeoutMs)});if(!res.ok)throw Object.assign(new Error(`google_custom_search_http_${res.status}`),{status:res.status});const data=await res.json();return{provider:'google_custom_search',status:'healthy',results:(Array.isArray(data?.items)?data.items:[]).map(x=>normalized({provider:'google_custom_search',title:x.title,url:x.link,snippet:x.snippet,publication:x.displayLink,raw:{mime:x.mime||null}}))}}
async function duckDuckGoInstant(query,{limit=6,fetchImpl=fetch,timeoutMs=7000}={}){const url=new URL('https://api.duckduckgo.com/');url.searchParams.set('q',text(query,1000));url.searchParams.set('format','json');url.searchParams.set('no_html','1');url.searchParams.set('skip_disambig','0');const res=await fetchImpl(url,{headers:{Accept:'application/json'},signal:timeout(timeoutMs)});if(!res.ok)throw Object.assign(new Error(`duckduckgo_http_${res.status}`),{status:res.status});const data=await res.json();const rows=[];if(data?.AbstractURL&&data?.AbstractText)rows.push(normalized({provider:'duckduckgo',title:data.Heading||query,url:data.AbstractURL,snippet:data.AbstractText,publication:data.AbstractSource||null}));const related=[];for(const item of Array.isArray(data?.RelatedTopics)?data.RelatedTopics:[]){if(item?.FirstURL)related.push(item);else if(Array.isArray(item?.Topics))related.push(...item.Topics)}for(const x of related.slice(0,Math.max(0,Number(limit)-rows.length)))rows.push(normalized({provider:'duckduckgo',title:x.Text?.split(' - ')[0]||query,url:x.FirstURL,snippet:x.Text||''}));return{provider:'duckduckgo',status:'healthy',results:rows}}
const providers={tavily:tavilySearch,brave:braveSearch,google_custom_search:googleCustomSearch,duckduckgo:duckDuckGoInstant};
export function providerConfiguration(){return{version:WEB_SEARCH_PROVIDERS_VERSION,providers:[{id:'tavily',configured:Boolean(process.env.TAVILY_API_KEY),mode:'authorized_api'},{id:'brave',configured:Boolean(process.env.BRAVE_SEARCH_API_KEY),mode:'official_api'},{id:'google_custom_search',configured:Boolean(process.env.GOOGLE_CUSTOM_SEARCH_API_KEY&&process.env.GOOGLE_CUSTOM_SEARCH_ENGINE_ID),mode:'legacy_official_api',lifecycle:'sunset_2027-01-01'},{id:'duckduckgo',configured:true,mode:'instant_answer_api',coverage:'not_full_web_search'},{id:'bing_search_legacy',configured:false,mode:'retired',lifecycle:'retired_2025-08-11'}]}}
export async function searchWebProviders(query,{providerIds,limit=8,fetchImpl=fetch,timeoutMs=9000}={}){const requested=Array.isArray(providerIds)&&providerIds.length?providerIds:['tavily','brave','google_custom_search','duckduckgo'];const started=Date.now();const ids=requested.filter(id=>providers[id]);const settled=await Promise.allSettled(ids.map(async id=>({id,result:await providers[id](query,{limit,fetchImpl,timeoutMs})})));const results=[],status=[];settled.forEach((item,index)=>{const id=ids[index];if(item.status==='fulfilled'){const result=item.value.result;results.push(...result.results);status.push({provider:id,status:result.status,count:result.results.length})}else status.push({provider:id,status:'degraded',count:0,error:text(item.reason?.message||item.reason,180)})});return{version:WEB_SEARCH_PROVIDERS_VERSION,results,status,latencyMs:Date.now()-started}}
