import { listSources, findSourceByUrl, discoverSourceCandidateFromUrl, sourceRegistryHealth } from './source-registry-v1.js';
import { buildResearchPlan, classifyResearchDomain, classifyFreshnessRequirement, deduplicateEvidence, scoreSourceAuthority, detectEvidenceContradictions, createCitation } from './engines-v1.js';
import { searchWebProviders, providerConfiguration } from './providers-v1.js';
import { webSecurityHealth } from './security-v1.js';
export const UNIVERSAL_WEB_INTELLIGENCE_VERSION='universal-web-intelligence/v1.0.0';
const CACHE=new Map();
const METRICS={requests:0,cacheHits:0,totalLatencyMs:0,totalDiscovered:0,totalDeduplicated:0,citationCoverageSum:0,contradictionCount:0,sourceDiversitySum:0,providerCalls:0,providerFailures:0,freshnessCounts:{STATIC:0,LOW:0,MEDIUM:0,HIGH:0,REAL_TIME:0}};
const ttlMs={STATIC:86400000*30,LOW:86400000*7,MEDIUM:3600000*12,HIGH:900000,REAL_TIME:60000};
const text=(v,max=2000)=>String(v??'').replace(/\u0000/g,'').replace(/\s+/g,' ').trim().slice(0,max);
function cacheGet(key,requirement){const row=CACHE.get(key);return row&&Date.now()-row.at<(ttlMs[requirement]||3600000)?row.value:null}
function cacheSet(key,value){CACHE.set(key,{at:Date.now(),value});if(CACHE.size>250)CACHE.delete(CACHE.keys().next().value)}
function sourceTier(record={}){const s=record.registrySource||{};if(s.primarySource&&s.officialSource)return 1;if(s.governmentSource)return 2;if(s.category==='law'&&s.officialSource)return 3;if(s.sourceType==='intergovernmental'||s.category==='government_data')return 4;if(s.academicSource)return 6;if(['technology','ai','cybersecurity'].includes(s.category)&&s.primarySource)return 7;if(s.category==='news')return 10;if(s.communitySource)return 12;return 11}
export async function researchWeb(query,options={}){const started=Date.now(),q=text(query,1500);METRICS.requests+=1;if(!q)throw Object.assign(new Error('web_query_required'),{status:400});const domain=options.domain||classifyResearchDomain(q),freshnessRequirement=options.freshnessRequirement||classifyFreshnessRequirement(q,domain),plan=buildResearchPlan(q,{domain,freshnessRequirement}),providerIds=Array.isArray(options.providers)?options.providers:undefined,limit=Math.max(3,Math.min(Number(options.limit)||12,30));const key=JSON.stringify([q.toLowerCase(),domain,freshnessRequirement,providerIds||'auto',limit]);if(options.cache!==false){const cached=cacheGet(key,freshnessRequirement);if(cached){METRICS.cacheHits+=1;return{...cached,requestId:options.requestId||crypto.randomUUID(),cacheHit:true,totalLatencyMs:Date.now()-started}}}const discovered=await searchWebProviders(q,{providerIds,limit:Math.min(limit,12),fetchImpl:options.fetchImpl||fetch,timeoutMs:options.timeoutMs||9000});METRICS.providerCalls+=discovered.status.length;METRICS.providerFailures+=discovered.status.filter(x=>['degraded','offline','rate_limited'].includes(x.status)).length;const deduped=deduplicateEvidence(discovered.results).map(item=>({...item,registrySource:findSourceByUrl(item.url||'')||discoverSourceCandidateFromUrl(item.url||'')}));const ranked=deduped.map(item=>({...item,authority:scoreSourceAuthority(item,{corroborationCount:item.corroborationCount||1,freshnessRequirement}),sourceTier:sourceTier(item)})).sort((a,b)=>(a.sourceTier-b.sourceTier)||((b.authority?.trustScore||0)-(a.authority?.trustScore||0))).slice(0,limit);const contradictions=detectEvidenceContradictions(ranked),citations=ranked.map(createCitation);const result={version:UNIVERSAL_WEB_INTELLIGENCE_VERSION,requestId:options.requestId||crypto.randomUUID(),query:q,domain,freshnessRequirement,plan,providers:discovered.status,discoveredCount:discovered.results.length,deduplicatedCount:deduped.length,evidence:ranked,citations,contradictions,sourceDiversity:new Set(ranked.map(x=>x.registrySource?.id||(()=>{try{return new URL(x.url).hostname}catch{return null}})()).filter(Boolean)).size,citationCoverage:ranked.length?citations.filter(x=>x.url).length/ranked.length:0,researchLatencyMs:Date.now()-started,totalLatencyMs:Date.now()-started,cacheHit:false,generatedAt:new Date().toISOString()};METRICS.totalLatencyMs+=result.totalLatencyMs;METRICS.totalDiscovered+=result.discoveredCount;METRICS.totalDeduplicated+=result.deduplicatedCount;METRICS.citationCoverageSum+=result.citationCoverage;METRICS.contradictionCount+=result.contradictions.length;METRICS.sourceDiversitySum+=result.sourceDiversity;METRICS.freshnessCounts[freshnessRequirement]=(METRICS.freshnessCounts[freshnessRequirement]||0)+1;cacheSet(key,{...result,requestId:null});return result}
export function webIntelligenceMetrics(){const r=Math.max(1,METRICS.requests-METRICS.cacheHits),calls=Math.max(1,METRICS.providerCalls);return{version:UNIVERSAL_WEB_INTELLIGENCE_VERSION,requests:METRICS.requests,cacheHits:METRICS.cacheHits,cacheHitRate:METRICS.requests?Number((METRICS.cacheHits/METRICS.requests).toFixed(3)):0,averageResearchLatencyMs:Number((METRICS.totalLatencyMs/r).toFixed(1)),providerSuccessRate:METRICS.providerCalls?Number(((METRICS.providerCalls-METRICS.providerFailures)/calls).toFixed(3)):null,duplicateRatio:METRICS.totalDiscovered?Number((1-METRICS.totalDeduplicated/METRICS.totalDiscovered).toFixed(3)):0,averageCitationCoverage:Number((METRICS.citationCoverageSum/r).toFixed(3)),contradictionsDetected:METRICS.contradictionCount,averageSourceDiversity:Number((METRICS.sourceDiversitySum/r).toFixed(2)),freshnessRequests:{...METRICS.freshnessCounts},hallucinationRate:'measured_by_evals_not_runtime',factualAccuracy:'measured_by_evals_not_runtime'}}
export function webIntelligenceHealth(){return{version:UNIVERSAL_WEB_INTELLIGENCE_VERSION,status:'configured',registry:sourceRegistryHealth(),providers:providerConfiguration(),security:webSecurityHealth(),cacheEntries:CACHE.size,metrics:webIntelligenceMetrics(),capabilities:['intent/domain classification','query planning','multi-provider discovery','source authority scoring','freshness classification','deduplication','contradiction detection','citation provenance','source registry','prompt-injection sanitization','SSRF controls']}}
export function webSourceRegistry({category}={}){return{version:UNIVERSAL_WEB_INTELLIGENCE_VERSION,...sourceRegistryHealth(),sources:listSources({category})}}
